language: csharp
git:
  depth: false  # "Shallow clone detected during the analysis"
matrix:
  fast_finish: true
  include:
  - dotnet: 2.1.500
    mono: none
  - dotnet: 2.1  # latest available release
    mono: none  
    env: 
      - WITH_SONAR_ANALYSIS=true
      - TEST_RESULTS_PATH=./Mastercard.Developer.OAuth1Signer.Tests/bin
solution: Mastercard.Developer.OAuth1Signer.sln
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
install:
  - dotnet restore
  - test $WITH_SONAR_ANALYSIS && dotnet tool install --global dotnet-sonarscanner
before_script:
  - |
    test $WITH_SONAR_ANALYSIS && dotnet sonarscanner begin \
    /k:"$SONAR_PROJECT_KEY" \
    /n:"$SONAR_PROJECT_NAME" \
    /d:sonar.organization="$SONAR_ORGANIZATION_KEY" \
    /d:sonar.host.url="$SONAR_URL" \
    /d:sonar.login="$SONAR_TOKEN" \
    /d:sonar.cs.vstest.reportsPaths="${TEST_RESULTS_PATH}/tests.trx" \
    /d:sonar.cs.opencover.reportsPaths="${TEST_RESULTS_PATH}/coverage.xml"
script:
  - dotnet test -c Release -l:"trx;LogFileName=tests.trx" -r:"bin/" /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput="bin/coverage.xml"
  - dotnet publish -c Release
after_success:
  - test $WITH_SONAR_ANALYSIS && dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"