language: csharp
matrix:
  include:
    - dotnet: 2.1.400
      mono: none
    - dotnet: 2.1     # latest available release
      mono: none
solution: Mastercard.Developer.OAuth1Signer.sln
script:
  - dotnet restore
  - dotnet test -c Release
  - dotnet publish -c Release