language: csharp
matrix:
  include:
    - dotnet: 2.1.500
      mono: none
    - dotnet: 2.1     # latest available release
      mono: none
solution: Mastercard.Developer.OAuth1Signer.sln
install:
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet restore
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
  - |
    dotnet sonarscanner begin \
    /k:"$SONAR_PROJECT_KEY" \
    /d:sonar.organization="$SONAR_ORGANIZATION_KEY" \
    /d:sonar.host.url="$SONAR_URL" \
    /d:sonar.login="$SONAR_TOKEN" \
    /d:sonar.cs.vstest.reportsPaths="./Mastercard.Developer.OAuth1Signer.Tests/TestResults/results.trx"
  - dotnet test -c Release -l:"trx;LogFileName=results.trx"
  - dotnet publish -c Release
  - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"