language: csharp
matrix:
  include:
    - dotnet: 2.1.300 # first .NET Core 2.1 SDK release
    - dotnet: 2.1     # latest available release
solution: Mastercard.Developer.OAuth1Signer.sln
script:
  - dotnet restore
  - dotnet test -c Release
  - dotnet publish -c Release