language: csharp
matrix:
  include:
    - dotnet: 2.1.500
      mono: none
    - dotnet: 2.1     # latest available release
      mono: none
solution: Mastercard.Developer.OAuth1Signer.sln
install:
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet restore
script:
  - dotnet test -c Release
  - dotnet publish -c Release